### PR TITLE
[AMDGPU] handle core clocks below 500 MHz

### LINKED ISSUE #725: incorrect GPU information
MangoHud is displaying incorrect GPU information, at least clocks and power consumption on AMD systems.
Please see the attached video which shows MangoHud and CPU-X.

System information:
* Manjaro Linux, up 2 date
* Kernel 5.16.14-1-MANJARO
* Mesa 21.3.7-2
* MangoHud 0.6.6.1.r181.g284ae0d-1
* KDE Plasma 5.23.4
* Wayland session
* CPU: AMD Ryzen 7 5800X
* GPU: AMD Radeon RX 6900 XT
* RAM: 32 GB DDR4-3600

https://user-images.githubusercontent.com/36689675/162048546-f6845a17-e88b-46a9-b03d-4d096ec911b1.mp4

### PR DESCRIPTION
**Pull request by Mr-nUUb**
Core clocks are somewhat flaky on certain cards (e.g. readouts of 4 MHz and the likes).
Other tools clamp invalid readouts to 500 MHz.

Add 2 more options to handle invalid readings:
* clamp readouts to a certain threshold
* do not add invalid readouts to the average

Go with the latter approach to not falsify readouts and average.
Fixes #725 

EDIT: fix typo

### CODE REVIEW

**Comment by gort818** [comment]
Did you test with 08431a0221623fa83e3c884ccc0b03e53f7a7eda? Clocks should not be below 500 MHz as we are grabbing the current gfx clock directly from amdpu_metrics which does not report anything below 500 MHz

**Comment by Mr-nUUb** [comment]
> Did you test with [08431a0](https://github.com/flightlessmango/MangoHud/commit/08431a0221623fa83e3c884ccc0b03e53f7a7eda)? Clocks should not be below 500 MHz as we are grabbing the current gfx clock directly from amdpu_metrics which does not report anything below 500 MHz

I didn't update in quite some time and missed this commit. It is fixed now: on loading screens it goes down to 500 MHz and during load it goes up to ~2.7 GHz.

**Comment by Mr-nUUb** [comment]
@gort818 It still displays values below 500 MHz.
grafik

**Comment by gort818** [comment]
Looks like you are on the release version, that commit is the first commit after V0.6.8

**Comment by Mr-nUUb** [comment]
Ah crap, I thought it was before v0.6.8 -.-
My bad. I did a rebuild from source, thought it's fine and then installed the repo package.

**Comment by gort818** [comment]
Is this PR still relevant?

**Comment by Mr-nUUb** [comment]
Nope, will close it now.

**Pull request closed without merging**
