### PR TITLE
Logging options

### PR DESCRIPTION
**Pull request by larskraemer**
Referencing #229. I added a few config options for what should be logged.
The code is a bit ugly; I didn't want to be too fancy because I don't really know the codebase.

### CODE REVIEW

**Comment by flightlessmango** [comment]
I think everything can be logged regardless of if the param is enabled

**Comment by larskraemer** [comment]
Should I just take out the config options then and make it log everything always?

**Comment by flightlessmango** [comment]
Yes that sounds good

**Comment by larskraemer** [comment]
Alright, apart from the messed up commit history, this should work fine.
Should I add more information to the log, like memory usage etc.?

**Comment by jazztickets** [comment]
I'd like to see ram and vram added as well.

**Comment by flightlessmango** [comment]
I think this is good, just needs to be resolved

**Comment by jackun** [comment]
Mem usage needs a `loggingOn` check too

**Comment by jackun** [comment]
@larskraemer can you rebase with `git rebase -i 58f0dc4040b83e4ba6f96cb9fa88d9966bbda064` or some such and drop unrelated commits and then rebase on `develop`? But at least git itself drops these as duplicates anyway when rebasing.

**Comment by larskraemer** [comment]
Should be better now..

**Comment by jackun** [comment]
Crap, at least amdgpu file handles aren't opened if they are initially disabled.
> 72.001,1,0,44,0,0,0,0,0,100129

**Comment by larskraemer** [comment]
@jackun That is indeed a problem.. I changed the `init_gpu_stats` function to always try to initialize the GPU and disable the GPU overlay if it fails. In that case, we should just see '0' in the logs as before, which I think is sensible

**Comment by flightlessmango** [comment]
I'm confused by f850ccfeaa756356bee98557cf9337486fd778d7, now it won't show current ram unless it's logging?

**Comment by larskraemer** [comment]
It won't show RAM _unless_ it's logging? Does it at least not log the RAM anyway?

**Comment by flightlessmango** [comment]
I misunderstood, the code is fine. We just need the same thing for a bunch of others that are disabled if the param is disabled

**Comment by larskraemer** [comment]
I think I covered every param check for the things we are logging:

- `fps` is updated anyway
- `cpu_load` and `cpu_temp` are updated by `UpdateCPUData`, which has a check for `loggingOn`
- `gpu_load`, `gpu_temp`, `gpu_core_clock` and `gpu_mem_clock` are updated by `get*GpuInfo`, which has a check
- `ram_used` is updated by `update_meminfo`, which also has a check

**Comment by jackun** [comment]
Did you have plans for overlay_params? Doesn't seem to get used currently.

**Comment by jazztickets** [comment]
Can we get the .csv extension added to the log file while we're at it? It makes it easier for the folks who like to import the logs into LibreOffice calc or other programs. Although we'd want to wrap quotes around the values in the 2nd line of the log, where it displays the system info, just in case a comma appears in one of the values.

**Comment by larskraemer** [comment]
Ah, I forgot to remove that, it was to allow the user to configure what gets logged. Since we are now logging everything, it's not needed anymore. I will remove it after rebasing onto develop... again

**Pull request merged**
