### PR TITLE
Use the std::chrono convenience classes for timing

### PR DESCRIPTION
**Pull request by larskraemer**
I created a `MesaClock` class to wrap the `os_time_get_nano` function and replaced most timing calculations with `chrono`s helper classes. This lets us write things like `elapsedTime >= chrono::seconds(12)`, or `elapsedTime >= 12s`, which is much easier to read than `elapsedTime/1000000 >= 12`.

@jackun I would like to use a `Clock::duration` for the values in the `overlay_params` struct, too, however it is declared as `extern C` (in fact, the whole header is). I'm not sure why that is, it doesn't seem like it is included in any C-files.

### CODE REVIEW

**Comment by jackun** [comment]
Don't remember but maybe std::chrono::high_resolution_clock etc already uses `clock_gettime`?

**Comment by larskraemer** [comment]
It probably does. The only differences would probably be on Windows, if at all.
Using `high_resolution_clock` instead is as easy as changing the `using Clock=MesaClock;` line into `using Clock=std::chrono::high_resolution_clock;`
Frankly, I'd trust the standard library to provide a good high-resolution clock, so if you think we should use that instead, I'll change it.

**Comment by jackun** [comment]
> I'd trust the standard library to provide a good high-resolution clock,

Hmm, probably needs some "research", but might as well use "MesaClock" for now, then at least you know what you get.

**Comment by larskraemer** [comment]
According to Microsoft, `steady_clock` and `high_resolution_clock` use [`QueryPerformanceCounter`](https://docs.microsoft.com/en-us/cpp/standard-library/chrono?view=vs-2019), same as the implementation in `mesa/util/os_time.c`.
libcxx typedef's `high_resolution_clock` to `steady_clock`, which in turn uses `clock_gettime`

**Pull request merged**
