### PR TITLE
Add core_bars for a per CPU core load histogram

### PR DESCRIPTION
**Pull request by jansol**
Decided to take a stab at the core histogram I mentioned in #1038 

Not sure if it solves OP's problem there, but for me I find that it helps get a rough idea of the structure of the CPU load.

Screenshot

### CODE REVIEW

**Comment by flightlessmango** [comment]
Look goods. The only thing I'm thinking about is we want this to be displayed with `full` or not. Seems like overkill to have `core_load` and `core_bars` in `full`

**Comment by jansol** [comment]
Yeah having both is definitely unnecessary and which one should be there by default is up for debate. On one hand the numbers are more precise but the bars are better at giving an overview. I'm fine with any arbitrary decision in that regard - `full` is ultimately just a convenience macro. I guess the main question is how stable people expect `full` to be across versions?

Another option that would be cool would be to draw the load numbers right on top of the bars (vertically?) and use that to replace `core_load` completely, but I am not sure if imgui lets us do that without an unnecessary amount of work(arounds).

**Comment by flightlessmango** [comment]
Yeah let's not change the `full` for now. 

Can you set core_bars to false here          https://github.com/flightlessmango/MangoHud/blob/41f923b0b2be07f035df221d01625e11f1305fde/src/overlay_params.cpp#L733

and here
https://github.com/flightlessmango/MangoHud/blob/41f923b0b2be07f035df221d01625e11f1305fde/src/overlay_params.cpp#L544

**Comment by jansol** [comment]
I've been thinking, maybe it makes most sense to have this as a modifier option that is off by default like `histogram` for frametime?

**Comment by flightlessmango** [comment]
You need to set core_bars to false here

https://github.com/flightlessmango/MangoHud/blob/08152325d4b8a168dab460c0afd1d49e29cea2d8/src/overlay_params.cpp#L568

and also here
https://github.com/flightlessmango/MangoHud/blob/08152325d4b8a168dab460c0afd1d49e29cea2d8/src/overlay_params.cpp#L752

Otherwise it will be enabled with `full`

Also it appears core_bars is enabled by default? As just setting `core_load` gives the bars

**Comment by jansol** [comment]
Should work now. At least core_load alone gives me numbers, core_bars alone does nothing and adding both gives me the bars as expected.

**Comment by jansol** [comment]
I ran into a segfault somewhere in dbus when trying with `full` so couldn't verify that one but somehow I don't think that is related to these changes.

**Comment by axet** [comment]
Should be visually different 100% load from 99% load per core. By color, number, shape...

**Comment by jansol** [comment]
> Should be visually different 100% load from 99% load per core. By color, number, shape...

Yeah I would have loved that as well but didn't find an easy way to do it in the imgui histogram function. If someone finds a way or wants to take the time to write a custom drawing routine for this I would love to see it. To me personally it's not important enough to justify spending a lot of time on it, though. The current implementation already tells me what I want to know.

**Comment by flightlessmango** [comment]
> By color, number, shape

This is probably doable using ImPlot which is included in mangohud

**Pull request merged**
