### PR TITLE
Fix the tests and add push/pr CI setup

### PR DESCRIPTION
**Pull request by evelikov**
Nothing too controversial there I believe, but shout if you thing anything needs more polish.

The biggest piece that comes off the top of my head is more CI testing. Namely, there are various references about Windows across the build/code, although it's not clear:
 - what is the magical `meson -Dfoo=disabled -Dbar=enabled` combination that should be used
 - are both MSVC and MINGW supported - which versions
 
 If anyone has pointers, I'm happy to wire those up as well

### CODE REVIEW

**Comment by evelikov** [comment]
Forgot the Vulkan fix - now CI should be a bit happier

**Comment by evelikov** [comment]
Closes: https://github.com/flightlessmango/MangoHud/issues/927

@jbeich can you give this a try? It should resolve the Vulkan build issue you're seeing

**Comment by jbeich** [comment]
Sorry, I can't test as MangoHud doesn't build without [patches](https://github.com/freebsd/freebsd-ports/tree/main/benchmarks/mangohud/files) on FreeBSD. I don't even use MangoHud, so only filed #927 to help @danfe who maintains the package.

Looking at the commits here I don't see anything that would fix #927. `use_system_vulkan` option is `disabled` by default, and Ubuntu 22.04 (on CI) has Vulkan 1.3.204 but the affected version is 1.3.241 (37 versions ahead).

**Comment by jbeich** [comment]
Note, #927 explicitly mentions `-Duse_system_vulkan=enabled` thus you cannot use `Closes #927` unless you drop `use_system_vulkan` entirely.

**Comment by evelikov** [comment]
@jbeich [meson: do not pick system vulkan, when explicitly disabled](https://github.com/flightlessmango/MangoHud/pull/938/commits/cf5f0a84cad951269c1d8d037265d090902f09e0) fixes the exact same issues as the ones reported. Not sure what you meant with `... thus you cannot use Closes #927 unless you drop use_system_vulkan...`.

If you don't have the time to test this that's fine -  perhaps @danfe could?

**Comment by jbeich** [comment]
> the exact same issues as the ones reported

The error maybe the same but the cause is different. Downstream may explicitly pass `-Duse_system_vulkan=enabled` (like FreeBSD), so would still be affected. A proper fix would be something like https://github.com/haasn/libplacebo/commit/baec0e53c959 MangoHud needs to fix its `vk.xml` parser, similar to libplacebo.

**Comment by jbeich** [comment]
Err, s/libplacebo/Mesa/. MangoHud appears to use an old version of  `vk.xml` parser from Mesa.

- https://github.com/flightlessmango/MangoHud/blob/master/bin/gen_enum_to_str.py
- https://github.com/Mesa3D/mesa/blob/main/src/vulkan/util/gen_enum_to_str.py

**Comment by evelikov** [comment]
I get it, you're not interested in testing sorry for troubling you :bow:

**Comment by danfe** [comment]
> If you don't have the time to test this that's fine - perhaps @danfe could?

I will be updating FreeBSD port hopefully soonish™ and will try not to forget to take a closer look at this :) thanks for the heads-up!

**Comment by evelikov** [comment]
@flightlessmango your earlier commit d0f8c8aa9498b2feeb1e13f5cd8638cf8a4d6594 broke mangocontrol and mangoapp - perhaps you forgot to `git add`? Can we have this PR merged, so such mistakes are caught earlier

**Comment by evelikov** [comment]
> I have built mangohud with both in the past, but it's going to be borked because there will be unix specific things that need to be ifdef'd.
As for what version, I'm not sure. I've just used latest MINGW in arch

Thanks for the reference points. Will see if I can hook that up as follow-up.

**Pull request merged**
