### PR TITLE
Additional amdgpu temps

### PR DESCRIPTION
**Pull request by ademlabs**
Display additional temperatures for AMD GPU such as Junction and Memory temperature.
Based off the work of jackun's work from the [amdgpu-tj](https://github.com/flightlessmango/MangoHud/tree/amdgpu-tj) branch.

### CODE REVIEW

**Comment by flightlessmango** [comment]
This needs to be added to the `amdgpu.cpp` methods as well

**Comment by EduFrazao** [comment]
Very nice. Thanks @ademlabs and @jackun !!!

**Comment by leinardi** [comment]
Just curious, what's preventing the merge of this branch? It would be nice to be able to see the junction temp on the new releases.

**Comment by flightlessmango** [comment]
These features should be accompanied by parameters, otherwise I think this is done

**Comment by ademlabs** [comment]
Thanks for the feedback, I'll amend the MR with parameters.

**Comment by EduFrazao** [comment]
> Thanks for the feedback, I'll amend the MR with parameters.

Wow! What a nice feature. I'm looking forward to test this!
Thank you guys!

**Comment by ademlabs** [comment]
> These features should be accompanied by parameters, otherwise I think this is done

I added two new parameters: `gpu_junction_temp` and `gpu_mem_temp`
I updated the conf file as well as the README to reflect these.

Additionally, I moved the memory temperature to display on the VRAM line, which seems more appropriate + minor code updates for better readability.

**Comment by leinardi** [comment]
Just curious: anything that prevent this PR to be merged?

**Comment by EduFrazao** [comment]
> Just curious: is there anything that prevents this PR to get merged?

Yeah!! Very useful feature. Looking forward to test it!!

**Comment by leinardi** [comment]
@ademlabs I'm testing the branch `ademlabs:additional-amdgpu-temps`, but the additional temps are not showing.

I just cloned it, ran `git clean -xdf`, `./build.sh build` and `./build.sh install`.

This is my MangoHud.conf: https://gist.github.com/leinardi/3c34d6733e5e630ae483e8f4489ae97c

As you can see it has both `gpu_junction_temp` and `gpu_mem_temp`.

I have a 7900XTX and hwmon shows correctly all the temps (tested with `cat /sys/class/hwmon/hwmon9/temp2_input`).

`sensors` is also showing everything normally:
```
amdgpu-pci-1400
Adapter: PCI adapter
vddgfx:      399.00 mV 
fan1:           0 RPM  (min =    0 RPM, max = 3200 RPM)
edge:         +49.0°C  (crit = +100.0°C, hyst = -273.1°C)
                       (emerg = +105.0°C)
junction:     +51.0°C  (crit = +110.0°C, hyst = -273.1°C)
                       (emerg = +115.0°C)
mem:          +60.0°C  (crit = +108.0°C, hyst = -273.1°C)
                       (emerg = +113.0°C)
PPT:          21.00 W  (cap = 315.00 W)
```

Am I doing something wrong? I'm available to do some remote debug if you wish.

**Comment by ademlabs** [comment]
@leinardi Can you check if you have multiple MangoHud binaries in /usr/local/bin & /usr/bin?
The Git repo install puts it in local. I had a similar issue with my distro package of MangoHud and the Git version installed at the same time.

**Comment by leinardi** [comment]
@ademlabs thanks! That was exactly the issue: `whereis mangohud` showed multiple binaries. After removing them all and installing again from sources, it worked:
image

**Comment by EduFrazao** [comment]
Very nice. Hope this patch get merged before 0.6.9

**Comment by flightlessmango** [comment]
Merging with master is ugly and makes it harder to find potential issues.
Rebase your commits on top of master instead please

**Pull request closed without merging**
