### PR TITLE
using MAX temp for amdgpu temps, drop temp separation (mem and tunction)

### PR DESCRIPTION
**Pull request by axet**
Closing #1062

### CODE REVIEW

**Comment by flightlessmango** [comment]
Looks good, can you just squash the commits?

**Comment by axet** [comment]
ok. Gitlab has "squish commits" during the merging pull request. Strange github does't have it.

**Comment by flightlessmango** [comment]
It does exist but we have it disabled for *some* reason

**Comment by axet** [comment]
I also removed memory_temp and junction_temp. I guess I had to remove those from params and hud

**Comment by flightlessmango** [comment]
This makes `gpu_junction_temp` and `gpu_mem_temp` non-functional.
I would say make them functional again and if `gpu_junction_temp` is enabled then `gpu_temp` is temp1 and `gpu_junction_temp` is junction like it originally worked.

**Comment by siroccal** [comment]
This is a bad PR, because normal die temperature and junction temperature are both valuable information https://github.com/flightlessmango/MangoHud/issues/1062#issuecomment-1672380816. They're not the same thing and they should not be treated as if they're the same, because it's normal for junction temperature to be higher. If you want to see your junction temperature, just enable `gpu_junction_temp`...

> This makes `gpu_junction_temp` and `gpu_mem_temp` non-functional. I would say make them functional again and if `gpu_junction_temp` is enabled then `gpu_temp` is temp1 and `gpu_junction_temp` is junction like it originally worked.

No, it should always be clear what input is being displayed. If you mix data (e.g. with `max(gpu_temp, gpu_junction_temp)`), then you don't know if your average die temperature is too high even if junction temperature is not too high.

The way it works now (`gpu_temp` = `temp1_input`, `gpu_junction_temp` = `temp2_input`, and `gpu_mem_temp` = `temp3_input`) is good and should not be changed.

**Pull request closed without merging**
