### PR TITLE
Update cpu.cpp

### PR DESCRIPTION
**Pull request by AnorakMan**
fallback for k10temp method is passed the wrong path variable

### CODE REVIEW

**Comment by jackun** [comment]
Wrong path in what way?
This also simplifies down to `else if (name == "zenpower" || name == "k10temp")`

**Comment by AnorakMan** [comment]
On a system where the temperature file exists in "/sys/class/hwmon/hwmon2/temp1_input", but no Tdie file exists, then the loop exists with "path" set to hwmon0 instead of "hwmon2"

Then by the time the fallback method is run, it's looking in the wrong path.

**Comment by jackun** [comment]
"Tdie" is not a file but contents of `tempN_label`. What's in `cat /sys/class/hwmon/hwmon2/temp1_label`?

**Comment by AnorakMan** [comment]
I don't have a cat /sys/class/hwmon/hwmon2/temp1_label file

**Comment by jackun** [comment]
`find_temp_input` might need to be separately actually. Try 

```
...
else if (name == "zenpower" || name == "k10temp") {
    find_temp_input(path, input, "Tdie");
    break;
}
...
```

**Comment by AnorakMan** [comment]
Yeah, that ends up doing the same thing. My dodgy first attempt was just to force it to run the "find_temp_input" method before breaking. 
Thanks

**Pull request closed without merging**
